
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * Frame che contiene lo snowflake con i poligoni, i bottoni e il titolo.
 * @version 4.10.2019 
 * @author Marco Lorusso
 */
public class SnowFrame extends javax.swing.JFrame {
    
    /**
     * Creates new form SnowFrame
     */
    public SnowFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlePanel = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        ResetPoint = new javax.swing.JButton();
        SavePoint = new javax.swing.JButton();
        UploadPoint = new javax.swing.JButton();
        generateFlake = new javax.swing.JButton();
        SaveSVG = new javax.swing.JButton();
        framePanel = new javax.swing.JPanel();
        snowFlake = new SnowFlake();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1024, 768));
        setPreferredSize(new java.awt.Dimension(1024, 768));

        titlePanel.setBackground(new java.awt.Color(102, 204, 255));

        title.setFont(new java.awt.Font("Wide Latin", 1, 48)); // NOI18N
        title.setForeground(new java.awt.Color(255, 51, 102));
        title.setText("Snow flake");
        title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        title.setPreferredSize(new java.awt.Dimension(358, 48));

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titlePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 758, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titlePanelLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(titlePanel, java.awt.BorderLayout.PAGE_START);

        buttonPanel.setBackground(new java.awt.Color(102, 204, 255));

        ResetPoint.setBackground(java.awt.Color.orange);
        ResetPoint.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        ResetPoint.setText("Reset");
        ResetPoint.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ResetPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetPointActionPerformed(evt);
            }
        });

        SavePoint.setBackground(java.awt.Color.orange);
        SavePoint.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        SavePoint.setText("Save Pont");
        SavePoint.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        SavePoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SavePointActionPerformed(evt);
            }
        });

        UploadPoint.setBackground(java.awt.Color.orange);
        UploadPoint.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        UploadPoint.setText("Upload Point");
        UploadPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UploadPointActionPerformed(evt);
            }
        });

        generateFlake.setBackground(new java.awt.Color(255, 153, 51));
        generateFlake.setFont(new java.awt.Font("MS PGothic", 1, 36)); // NOI18N
        generateFlake.setText("Generate");
        generateFlake.setMaximumSize(new java.awt.Dimension(100, 50));
        generateFlake.setMinimumSize(new java.awt.Dimension(100, 50));
        generateFlake.setPreferredSize(new java.awt.Dimension(100, 65));
        generateFlake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateFlakeActionPerformed(evt);
            }
        });

        SaveSVG.setBackground(java.awt.Color.orange);
        SaveSVG.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        SaveSVG.setText("Save SVG");
        SaveSVG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveSVGActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(generateFlake, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(UploadPoint, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                    .addComponent(SavePoint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ResetPoint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SaveSVG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 51, Short.MAX_VALUE))
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(UploadPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(SavePoint, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(ResetPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(generateFlake, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(SaveSVG, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        getContentPane().add(buttonPanel, java.awt.BorderLayout.LINE_END);

        framePanel.setBackground(new java.awt.Color(0, 153, 255));
        framePanel.setLayout(new java.awt.BorderLayout());

        snowFlake.setBackground(new java.awt.Color(102, 204, 255));

        javax.swing.GroupLayout snowFlakeLayout = new javax.swing.GroupLayout(snowFlake);
        snowFlake.setLayout(snowFlakeLayout);
        snowFlakeLayout.setHorizontalGroup(
            snowFlakeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );
        snowFlakeLayout.setVerticalGroup(
            snowFlakeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1493, Short.MAX_VALUE)
        );

        framePanel.add(snowFlake, java.awt.BorderLayout.CENTER);

        getContentPane().add(framePanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ResetPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetPointActionPerformed
        SnowFlake.pol.clear();
        SnowFlake.pol.add(new Poligono(snowFlake));
        snowFlake.repaint();
    }//GEN-LAST:event_ResetPointActionPerformed

    private void SavePointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavePointActionPerformed
        snowFlake.savePoint();
    }//GEN-LAST:event_SavePointActionPerformed

    private void UploadPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UploadPointActionPerformed
        try {
            snowFlake.uploadPoint();
        } catch (IOException ex) {
            Logger.getLogger(SnowFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_UploadPointActionPerformed

    private void generateFlakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateFlakeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_generateFlakeActionPerformed

    private void SaveSVGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveSVGActionPerformed
        snowFlake.saveSvg();
    }//GEN-LAST:event_SaveSVGActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SnowFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SnowFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SnowFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SnowFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SnowFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ResetPoint;
    private javax.swing.JButton SavePoint;
    private javax.swing.JButton SaveSVG;
    private javax.swing.JButton UploadPoint;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel framePanel;
    private javax.swing.JButton generateFlake;
    private SnowFlake snowFlake;
    private javax.swing.JLabel title;
    private javax.swing.JPanel titlePanel;
    // End of variables declaration//GEN-END:variables
}
